name: Build Yocto Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull gateway-build-container image
      run: |
        docker pull ghcr.io/egrissino/gateway-build-container:latest

    - name: Build and run gateway-build-container
      run: |
        docker run --rm -v $(pwd):/workspace -w /workspace ghcr.io/egrissino/gateway-build-container:latest ./buildyocto.sh
